### ISSUE TITLE
Mobile: user card menu is not clickable

### ISSUE THREAD

**Issue by tiborsulyan** [FriendsOfFlarum/user-directory#56] opened 2021-01-02 00:15 UTC
Hi, 

On mobile browsers the menu of the user card is not usable.

This is the list:
![user_list_mobile_small](https://user-images.githubusercontent.com/1927167/103448255-38b39d00-4c97-11eb-8d51-1dd215759372.jpg)
I'm logged in with an admin user with permissions to edit user profiles. When I click on the menu of an user card, an overlay prevents tapping on the menu items:

![user_list_click_on_user_menu_small](https://user-images.githubusercontent.com/1927167/103448263-5123b780-4c97-11eb-9487-2928c93cc6a6.jpg)

It's behaving the same with chrome on android and safari on ios. I'm using Flarum beta 15 with FoF user directory 0.5.0 and FoF terms 0.6.1.

**Comment by clarkwinkelmann** [comment] 2021-01-02 02:27
Thanks for the report. It's a duplicate of #36

It seems fairly easy to reproduce, but I still don't know how we're going to fix this. This might need fixing at the Flarum level.

**Closed by clarkwinkelmann** 2021-01-02 02:27 UTC
