### ISSUE TITLE
Sidebar link visible when on user directory page

### ISSUE THREAD

**Issue by robinheidrich** [FriendsOfFlarum/user-directory#68] opened 2021-05-22 17:04 UTC
The sidebar link is disabled in the settings, but is still displayed only when you go to the user directory page.

I'm using version 0.6.2.

**Comment by clarkwinkelmann** [comment] 2021-05-22 18:03
That's intended behavior. It provides context about where the user is.

Also on mobile it becomes the name in the header in the side navigation switcher.

**Comment by imorland** [comment] 2021-05-26 13:57
Closing as this is intended behaviour

**Closed by imorland** 2021-05-26 13:57 UTC
Labels: bug
